version: "3.7"

services:
  nuxt-app:
   # build: ./nuxt-app
    image: blowstack/nuxt-app:latest
    container_name: nuxt-app
    restart: always
    ports:
      - "3000:3000"
    command: "npm run start"
    networks:
      - nuxt-network
  web-server:
    image: nginx:1.17.10-alpine
    container_name: web-server
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - web-root:/var/www/blowstack
    ports:
      - 80:80
    networks:
      nuxt-network:
    depends_on:
      - nuxt-app
    restart: unless-stopped
  db:
    image: mysql:8.0
    container_name: blowstack-mysql
    command: '--wait_timeout=28800 --default-authentication-plugin=mysql_native_password'
    volumes:
      - "mysql-data:/var/lib/docker/volumes/blowstack/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database_name
    ports:
      - "3307:3307"
    restart: always
    networks:
      - nuxt-network
volumes:
  web-root:
  mysql-data:
networks:
  nuxt-network:
    driver: bridge


